# build.yml

# 工作流程的名字
name: Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - 'v*'

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      # 提取仓库版本信息
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      # 使用仓库信息
      - name: Build base image
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      # 保存
      - name: Save version
        run: |
          echo '{"version":${{ steps.branch_name.outputs.SOURCE_TAG }}}' > version.json
      # 保存
      - name: Cat version
        run: |
          cat version.json
      # 发布到 内部服务器
      - name: Release apk to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '47.107.98.40'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "README.md"
          remote_path: '/root'
          args: '-o ConnectTimeout=10'