# build.yml

# 工作流程的名字
name: Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    tags:
      - 'v*'

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      # 发布到 内部服务器
      - name: Release apk to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '47.107.98.40'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "README.md"
          remote_path: '/usr/local/src/runtime/update/sps'
          args: '-o ConnectTimeout=10'